### ISSUE TITLE
Create a sub-sample of COM(P)ADRE to distribute with the package?

### ISSUE THREAD

**Issue by levisc8** [jonesor/Rcompadre#14]
Would it be worthwhile to include a subsample of one or both databases as example data sets? I suspect it will make our lives easier in the long run.

For example, we could then use something like `data(compadre)` in the vignettes and examples rather than relying on file paths to the objects (which change on every machine). 

If others agree with the general concept, I'm happy to work on identifying a good subsample from each data base to distribute with the package.

**Comment by jonesor** [comment]
Yes - I've been meaning to do this for a while, but I haven't gotten around to it yet.
We'd need enough species that the examples in the vignettes make sense (e.g. where there is subsetting by certain variables etc.). I'm happy to change the vignettes though. 
Go for it!

**Comment by levisc8** [comment]
I'll look through the current vignette and try to create subsets that don't require too much editing. Hopefully will have something up here by Monday!

**Comment by levisc8** [comment]
Sample data sets are now uploaded(5924510) and documented (f0f2b0f). I tried to include as many species from the vignette as possible, but ended up cutting out a few that may have made the data sets a bit too large.

The script to create them is in data-raw so you can review that if you'd like. I'll leave the issue open until you've had a chance to review the data sets.

**Comment by patrickbarks** [comment]
The sample datasets look great, and are super helpful for testing functions and writing examples. Just a few thoughts:

1. The Comadre set doesn't include any matrices from Africa or Asia, and has only one study from S America. I suggest targeting a few studies from each continent for the sake of geographic balance (though of course there are biases in the full db too).

2. In the `mergeDBs` function in createDataSets.R, if the user hasn't used `subsetDB`, `version$NumberStudies` is calculated as the number of unique species. I think this may have been an error imported from `subsetDB`. (Perhaps @jonesor can clarify how NumberStudies is officially calculated?).

3. This is more for @jonesor and @robcito, but the metadata columns differ between Comadre and Compadre in the most recent public releases (but I believe are consistent in newer, unreleased versions). It would be nice if the sample datasets in this package had consistent metadata columns, though I'm not sure the best way to achieve this. Perhaps build the sample datasets from the unreleased v.X.X.X database versions rather than the public versions?

**Comment by jonesor** [comment]
I can confirm that the metadata columns in the newest version of COMPADRE/COMADRE are consistent. 

NumberStudies is calculated as `length(unique(compadre$metadata$SpeciesAuthor))`. If you recall `SpeciesAuthor` is the species name, plus an integer suffix for subsequent papers that focus on that species. e.g. "Ovis_canadensis", then "Ovis_canadensis_2", then "Ovis_canadensis_3" and so on. 

The unreleased species in the X.X.X version are ones where we have some missing data or there are other problems with the matrix or associated metadata. Therefore, it may not be a great idea to release them into the world without careful checking (in which case they could be released in the next version anyway, so no problem!).

**Comment by jonesor** [comment]
We have had subsets of COMPADRE/COMADRE in the package for a while (accessed with `data(Compadre)` and `data(Comadre`) so I'm closing this.
