### ISSUE TITLE
Cut species/study/matrix counts from db@version

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rcompadre#42]
They...
- have no impact on reproducibility
- can be calculated from `db@data` using existing Rcompadre fns
- can become outdated with the use of `[`, `subset()`, `merge()`, etc. on `db@data`
- complicate `CompadreDB` methods such as `[`, and methods we might add in the future for `subset()`, `merge()`, etc.
  - e.g. if a user's column selection with `[` or `subset` doesn't include `YearPublication`, then `NumberStudies` can't be updated
  - incidently, the current `[` method _doesn't_ update species/study/matrix counts based on the given row subset, whereas `subsetDB` does

Also, the species and matrix counts (i.e. the underlying calculations) are already part of the `show` method, which at least ensures those counts are accurate at the time of printing.

The counts will still exist in the `version` element of legacy dbs, but I suggest we drop them during the `asCompadreData` conversion (and from other Rcompadre functions).

(I still think we should consider removing the whole `version` slot, but that's a separate issue)

**Comment by iainmstott** [comment]
I agree, it doesn't give anything really valuable in terms of versioning.

I will say I changed `NumberAcceptedSpecies`, `NumberStudies` and `NumberMatrices` methods so that they calculate the numbers directly from the object, rather than accessing them from the `Version` slot because I saw those problem with subsetting and merging databases. All the functions and methods _should_ give the right info, but only because I bypassed what's in the `Version` slot. 

This means also that users have methods available (although these should probably be made functions) to calculate these things independently, which makes them of even less use in the `Version` slot.

Let's ditch 'em

**Comment by jonesor** [comment]
I'm on board with this too.
I will update the code we use to compile the databases to take care of this from the next version of both compadre and comadre.

**Comment by patrickbarks** [comment]
Sounds good to me. Could also keep the Agreement. I have no preference either way.

**Comment by patrickbarks** [comment]
closed by #44
Reminder to @jonesor to update the next db releases accordingly
