### ISSUE TITLE
Create branch to preserve current (non-dev) version?

### ISSUE THREAD

**Issue by jonesor** [jonesor/Rcompadre#46]
We are getting close to the point where we will want to merge the changes we have made on the dev branch to those on the master branch. It has occurred to me that people might still be using or want to use the current version (e.g. they are currently working on analyses).  

We could, I think, create a new branch from the master before we merge the dev branch, and call it "v.0.1", or whatever, so that to install that old version you would simply need to use:

```
install_github("jonesor/Rcompadre",ref = "v.0.1")
```

What do you all think?

**Comment by levisc8** [comment]
I'd suggest creating a release instead. It generates a tarball of the current source that is downloadable through `install_github()` by appending the tag name to the repo (see below). You can tag it with whatever name you want, and then run

`devtools::install_github('jonesor/Rcompadre@tag_name')`

Having a separate branch for each release might get a bit messy when we reach higher version numbers.

**Comment by jonesor** [comment]
I have done that now - 
```
devtools::install_github('jonesor/Rcompadre@v0.1.0')
```

We should probably add a note about this to the readme when we merge dev with master.

**Comment by patrickbarks** [comment]
@jonesor: perhaps you were planning this anyway, but it occurs to me that Rage and Rcompadre should be merged into master at the same time because of their interdependencies:

- Rage@master depends on Rcompadre@master, and will break with Rcompadre@devel (because of those 4 functions that we moved)

- Rage@devel doesn't depend on Rcompadre

- The new ternary plot vignette in Rcompadre@devel depends on Rage@master (but will still work with Rage@devel)

**Comment by jonesor** [comment]
I have done this now (both packages) so closing this issue
