### ISSUE TITLE
matrix accessor functions return lists for all CompadreDB objects

### ISSUE THREAD

**Issue by iainmstott** [jonesor/Rcompadre#58]
I think `matA`, `matU`, `matF`, `matC` and any of the others in the ClassUnionMethods.R file _always_ return a list, even if the database passed is just one row. Intuitively one might want to use e.g.
`matA(compadre[123, ])` or `matA(compadre[123])` expecting a matrix, but getting a list of length 1 containing the matrix. We can get it with e.g. `matA(compadre$mat[[123]])`, but would be good for the others to work too.

**Comment by patrickbarks** [comment]
I prefer the current behavior. Having the type of return depend on the number of rows in `db` could be confusing — particularly when used with subsetting. E.g. If I want to subset a db and then calculate lambda for every row, I might use:

```
db_sub <- subset(db, column == "blah")
lambda_sub <- sapply(matA(db_sub), popbio::lambda)
```
I would expect this to work regardless of the size of my subset, which I might not know ahead of time. But if the subset turns out to be just 1 row, in which case `matA()` returns a matrix rather than a list, then instead of calculating 1 lambda per matrix, my `sapply` line will calculate 1 lambda for every element of the single matrix. Which is particularly scary because it wouldn't even throw an error in this case.

**Comment by iainmstott** [comment]
Oh yeah, good point, and I've seen plenty of other functions that do the same.

I think I'll stick a quick note in the documentation; at first instance it seems unintuitive (my student stumbled on it, and I also didn't twig when he emailed to ask why things weren't working)
