### ISSUE TITLE
Function to load local com(p)adre .Rdata files

### ISSUE THREAD

**Issue by wpetry** [jonesor/Rcompadre#93]
What would folks think about an accessor function to load local downloads of the databases? I'm imagining something like `read_cdb` that would be a simple wrapper of `load` and `as_cdb` with some error checking. I appreciate the motivation to keep the .Rdata files hosted online as lists rather than `CompadreDB` classed objects, but I suspect no one will ever use them in that form. Can we make the user's life easier by doing the coercion for them?

**Comment by wpetry** [comment]
Maybe it could also try to check whether the version being loaded is current or not, passing a warning if a newer version is available. If the database can't be checked (e.g., not connected to the internet), a warning should say so. Users could turn this off with a `warn_outdated = FALSE` argument.

**Comment by jonesor** [comment]
Funnily enough, I was thinking the same thing. The basic function would be pretty straightforward, so go for it!
For the extra bit (checking whether the version is current or not), are you going to do that by downloading the latest version and comparing it? If so, how will you do the comparison. 
We do have a basic `cdb_compare` function (which could definitely be improved.

**Comment by jonesor** [comment]
Hi @wpetry. I have now realised that the `cdb_fetch` function actually does this.

`x<-cdb_fetch("COMPADRE_v.5.0.0.RData")`

It DOESN'T check for a newer version, so that is an enhancement that could be added, but I think there are some complications with that. For example, one would need to tell the function WHICH database you are referring to (or you could infer this based on taxonomy information). Also, since the function could well be used to load subsetted versions of the DB, or even users' own compadre-class data it would need to be an option that can be turned off.

I am therefore closing this now, though we can revisit it later.
